name: eight_barrels
description: 8 Barrels Mobile Application

publish_to: 'none' 

version: 1.1.6+38

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  material_design_icons_flutter: ^6.0.7096
  font_awesome_flutter: ^10.1.0
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  intl: ^0.17.0
  get: ^4.6.5
  image_picker: ^0.8.7
  timelines: ^0.1.0
  location: ^4.3.0
  geolocator: ^9.0.2
  geocoding: ^2.0.2
  permission_handler: ^10.2.0
  keyboard_actions: ^4.1.0
  google_maps_place_picker:
    git: https://github.com/ERAKOMP-IT/google_maps_place_picker.git
#  google_maps_place_picker: ^2.1.0-nullsafety.3

  syncfusion_flutter_datepicker: ^21.1.35
  flutter_spinkit: ^5.1.0
  modal_progress_hud_nsn: ^0.3.0
  google_sign_in: ^6.0.2
  pull_to_refresh: ^2.0.0
  flutter_facebook_auth: ^5.0.8
  sign_in_with_apple: ^4.3.0
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  firebase_messaging: ^14.3.0
#  firebase_database: ^9.0.7
  carousel_slider: ^4.0.0
  cached_network_image: ^3.2.0
  flutter_local_notifications: ^14.0.0-dev.2
  package_info_plus: ^3.0.3
  shimmer: ^2.0.0
  flutter_multi_formatter: ^2.5.1
  readmore: ^2.1.0
  flutter_staggered_grid_view: ^0.6.1
  badges: ^3.0.2
  timeago: ^3.2.2
  pin_code_fields: ^7.3.0
  flutter_html: ^3.0.0-alpha.6
  webview_flutter: ^4.0.7
  sprintf: ^7.0.0
  uni_links: ^0.5.1
  flutter_rating_bar: ^4.0.0
  connectivity: ^3.0.6
  internet_connection_checker: ^1.0.0+1
  dotted_border: ^2.0.0
  flutter_secure_storage: ^8.0.0
  introduction_screen: ^3.0.2
  showcaseview: ^2.0.2
  flutter_share: ^2.0.0
  flutter_dotenv: ^5.0.2
  flutter_jailbreak_detection: ^1.8.0
  url_launcher: ^6.0.10
  flutter_inappwebview: ^5.7.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/locale/en.json
    - assets/locale/id.json
    - .env.development
    - .env.production
    - .env.local
  fonts:
    - family: Futura
      fonts:
        - asset: assets/fonts/futura/Futura-Book-font.ttf
        - asset: assets/fonts/futura/Futura-Book-Italic-font.ttf
          style: italic
